# Generated by Django 4.0.4 on 2022-04-14 01:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CauHinh',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ram', models.IntegerField(blank=True, default=0, null=True, verbose_name='Dung lượng RAM')),
                ('rom', models.IntegerField(blank=True, default=0, null=True, verbose_name='Dung lượng ROM')),
            ],
        ),
        migrations.CreateModel(
            name='DongSP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dongSP', models.CharField(max_length=50, verbose_name='Dòng sản phẩm')),
            ],
        ),
        migrations.CreateModel(
            name='SanPham',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten', models.CharField(default='Unknow', max_length=30, verbose_name='Tên sản phẩm')),
                ('moTa', models.TextField(default='Đang cập nhật', verbose_name='Mô tả')),
                ('doPG', models.CharField(blank=True, default='Đang cập nhật', max_length=20, null=True, verbose_name='Độ phân giải màn hình')),
                ('doSang', models.IntegerField(blank=True, default=0, null=True, verbose_name='Độ sáng tối đa')),
                ('matCU', models.CharField(blank=True, default='Đang cập nhật', max_length=20, null=True, verbose_name='Chất liệu mặt trước')),
                ('manHinh', models.DecimalField(blank=True, decimal_places=1, default=0, max_digits=2, null=True, verbose_name='Kích thước màn hình')),
                ('camTruoc', models.TextField(blank=True, default='Đang cập nhật', null=True, verbose_name='Thông số camera trước')),
                ('camSau', models.TextField(blank=True, default='Đang cập nhật', null=True, verbose_name='Thông số camera sau')),
                ('sim', models.TextField(blank=True, default='Đang cập nhật', null=True, verbose_name='Thông số về SIM')),
                ('IP', models.CharField(blank=True, default=0, max_length=5, null=True, verbose_name='Tiêu chuẩn kháng nước, bụi')),
                ('kt_tl', models.TextField(blank=True, default='Đang cập nhật', null=True, verbose_name='Kích thước, trọng lượng')),
                ('chatLieu', models.CharField(blank=True, default='Đang cập nhật', max_length=30, null=True, verbose_name='Chất liệu sản phẩm')),
                ('os', models.CharField(blank=True, default='Đang cập nhật', max_length=20, null=True, verbose_name='Hệ điều hành cài sẵn')),
                ('cpu', models.CharField(blank=True, default='Đang cập nhật', max_length=20, null=True, verbose_name='Chip xử lý')),
                ('cpu_clock', models.CharField(blank=True, default='GHz', max_length=10, null=True, verbose_name='Tốc độ xử lý')),
                ('gpu', models.CharField(blank=True, default='Đang cập nhật', max_length=20, null=True, verbose_name='Chip đồ họa')),
                ('pin', models.CharField(blank=True, default='mAh', max_length=20, null=True, verbose_name='Dung lượng pin')),
                ('loaiPin', models.CharField(blank=True, default='Đang cập nhật', max_length=20, null=True, verbose_name='Loại pin')),
                ('nguonSac', models.CharField(blank=True, default='w', max_length=10, null=True, verbose_name='Công suất sạc tối đa')),
                ('nam', models.CharField(blank=True, default=0, max_length=10, null=True, verbose_name='Năm ra mắt')),
                ('soLuong', models.IntegerField(blank=True, default=0, null=True, verbose_name='Số lượng sản phẩm')),
                ('trangThai', models.CharField(choices=[('KHÓA', 'Khóa'), ('MỞ', 'Mở'), ('HẾT_HÀNG', 'Hết hàng'), ('CHƯA_CÓ_HÀNG', 'Chưa có hàng')], default=('KHÓA', 'Khóa'), max_length=20, verbose_name='Trạng thái sản phẩm')),
                ('dongSP', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='ban_dt.dongsp', verbose_name='Dòng sản phẩm')),
            ],
        ),
        migrations.CreateModel(
            name='Mau',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten', models.CharField(blank=True, default='Đang cập nhật', max_length=20, null=True, verbose_name='Tên màu')),
                ('maMau', models.CharField(blank=True, default='Đang cập nhật', max_length=20, null=True, verbose_name='Mã màu')),
                ('sanPham', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ban_dt.sanpham', verbose_name='Sản phẩm')),
            ],
        ),
        migrations.CreateModel(
            name='Gia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gia', models.IntegerField(blank=True, default=0, null=True, verbose_name='Giá sản phẩm')),
                ('cauHinh', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ban_dt.cauhinh', verbose_name='Loại cấu hình')),
                ('mau', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ban_dt.mau', verbose_name='Loại màu')),
                ('sanPham', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ban_dt.sanpham', verbose_name='Sản phẩm')),
            ],
        ),
        migrations.AddField(
            model_name='cauhinh',
            name='sanPham',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ban_dt.sanpham', verbose_name='Sản phẩm'),
        ),
    ]
