# Generated by Django 4.0.4 on 2022-04-14 15:29

import ban_dt.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ban_dt', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ThuongHieu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten', models.CharField(blank=True, default='Đang cập nhật', max_length=40, null=True, verbose_name='Tên thương hiệu')),
            ],
        ),
        migrations.AddField(
            model_name='sanpham',
            name='slug',
            field=models.SlugField(blank=True, null=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='cauhinh',
            name='ram',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Dung lượng RAM'),
        ),
        migrations.AlterField(
            model_name='cauhinh',
            name='rom',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Dung lượng ROM'),
        ),
        migrations.AlterField(
            model_name='gia',
            name='gia',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Giá sản phẩm'),
        ),
        migrations.AlterField(
            model_name='sanpham',
            name='IP',
            field=models.CharField(blank=True, default=None, max_length=5, null=True, verbose_name='Tiêu chuẩn kháng nước, bụi'),
        ),
        migrations.AlterField(
            model_name='sanpham',
            name='doSang',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Độ sáng tối đa'),
        ),
        migrations.AlterField(
            model_name='sanpham',
            name='nam',
            field=models.CharField(blank=True, default=None, max_length=10, null=True, verbose_name='Năm ra mắt'),
        ),
        migrations.AlterField(
            model_name='sanpham',
            name='soLuong',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Số lượng sản phẩm'),
        ),
        migrations.AlterField(
            model_name='sanpham',
            name='trangThai',
            field=models.CharField(choices=[('Khóa', 'Khóa'), ('Mở', 'Mở'), ('Hết hàng', 'Hết Hàng'), ('Chưa có hàng', 'Chưa Có Hàng')], default='Khóa', max_length=20, verbose_name='Trạng thái sản phẩm'),
        ),
        migrations.CreateModel(
            name='PhanHoi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hoTen', models.CharField(blank=True, max_length=50, null=True, verbose_name='Họ tên người đăng')),
                ('soDT', models.CharField(blank=True, max_length=10, null=True, validators=[ban_dt.models.validate_number], verbose_name='Số điện thoại')),
                ('ngayDang', models.DateTimeField(auto_now_add=True, verbose_name='Ngày đăng')),
                ('noiDung', models.TextField(verbose_name='Nội dung bình luận')),
                ('sanPham', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ban_dt.sanpham', verbose_name='Sản phẩm')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Người dùng')),
            ],
        ),
        migrations.CreateModel(
            name='HoaDon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ngayLap', models.DateTimeField(auto_now=True, verbose_name='Ngày lập hóa đơn')),
                ('tongTien', models.PositiveIntegerField(default=0, verbose_name='Tổng tiền')),
                ('trangThai', models.CharField(choices=[('Đang xác nhận', 'Đang Xác Nhận'), ('Đã xác nhận', 'Đã Xác Nhận'), ('Hoàn tất', 'Hoàn Tất'), ('Đã hủy', 'Đã Hủy')], default='Đang xác nhận', max_length=15, verbose_name='Trạng thái')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Người dùng')),
            ],
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ngaySinh', models.DateField(blank=True, null=True, verbose_name='Ngày sinh')),
                ('soDT', models.CharField(blank=True, max_length=10, null=True, validators=[ban_dt.models.validate_number], verbose_name='Số điện thoại')),
                ('diaChi', models.CharField(blank=True, default='Đang cập nhật', max_length=50, null=True, verbose_name='Địa chỉ')),
                ('trangThai', models.CharField(choices=[('Khóa', 'Khóa'), ('Mở', 'Mở'), ('XÓA', 'Xóa')], default='Khóa', max_length=10, verbose_name='Trạng thái người dùng')),
                ('user', models.OneToOneField(auto_created=True, editable=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ChiTietHoaDon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('soLuong', models.PositiveSmallIntegerField(default=1, verbose_name='Số lượng')),
                ('donGia', models.PositiveIntegerField(default=0, verbose_name='Đơn giá')),
                ('hoaDon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ban_dt.hoadon', verbose_name='Hóa đơn')),
                ('sanPham', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ban_dt.sanpham', verbose_name='Sản phẩm')),
            ],
        ),
        migrations.CreateModel(
            name='ChiTietGioHang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='ban_dt.gia', verbose_name='Giá sản phẩm')),
                ('sanPham', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='ban_dt.sanpham', verbose_name='Sản phẩm')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BinhLuan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hoTen', models.CharField(blank=True, max_length=50, null=True, verbose_name='Họ tên người đăng')),
                ('soDT', models.CharField(blank=True, max_length=10, null=True, validators=[ban_dt.models.validate_number], verbose_name='Số điện thoại')),
                ('ngayDang', models.DateTimeField(auto_now_add=True, verbose_name='Ngày đăng')),
                ('noiDung', models.TextField(verbose_name='Nội dung bình luận')),
                ('sanPham', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ban_dt.sanpham', verbose_name='Sản phẩm')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Người dùng')),
            ],
        ),
        migrations.AddField(
            model_name='dongsp',
            name='ThuongHieu',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ban_dt.thuonghieu', verbose_name='Thương hiệu'),
        ),
        migrations.AddField(
            model_name='sanpham',
            name='ThuongHieu',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ban_dt.thuonghieu', verbose_name='Thương hiệu'),
        ),
    ]
