# Generated by Django 4.0.4 on 2022-04-16 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ban_dt', '0004_alter_anh_uri'),
    ]

    operations = [
        migrations.AddField(
            model_name='anh',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='media/', verbose_name='File ảnh'),
        ),
        migrations.AddField(
            model_name='anh',
            name='loaiAnh',
            field=models.CharField(choices=[('Banner', 'Banner'), ('Product', 'Product')], default='Product', max_length=7),
        ),
        migrations.AlterField(
            model_name='anh',
            name='uri',
            field=models.URLField(blank=True, null=True, verbose_name='File ảnh'),
        ),
    ]
