# Generated by Django 4.0.4 on 2022-04-14 15:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ban_dt', '0002_thuonghieu_sanpham_slug_alter_cauhinh_ram_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Anh',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten', models.CharField(max_length=20)),
                ('uri', models.URLField(verbose_name='Đường dẫn')),
                ('sanPham', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ban_dt.sanpham', verbose_name='Thuộc sản phẩm')),
            ],
        ),
    ]
