# Generated by Django 4.0.4 on 2022-04-16 07:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ban_dt', '0005_anh_file_anh_loaianh_alter_anh_uri'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='phanhoi',
            name='sanPham',
        ),
        migrations.AddField(
            model_name='phanhoi',
            name='binhLuan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ban_dt.binhluan', verbose_name='Bình luận'),
        ),
        migrations.AlterField(
            model_name='chitietgiohang',
            name='gia',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Giá sản phẩm'),
        ),
        migrations.AlterField(
            model_name='hoadon',
            name='tongTien',
            field=models.PositiveBigIntegerField(default=0, verbose_name='Tổng tiền'),
        ),
        migrations.AlterField(
            model_name='sanpham',
            name='cpu_clock',
            field=models.CharField(blank=True, default='NaN GHz', max_length=10, null=True, verbose_name='Tốc độ xử lý'),
        ),
        migrations.AlterField(
            model_name='sanpham',
            name='nguonSac',
            field=models.CharField(blank=True, default='NaN w', max_length=10, null=True, verbose_name='Công suất sạc tối đa'),
        ),
        migrations.AlterField(
            model_name='sanpham',
            name='pin',
            field=models.CharField(blank=True, default='NaN mAh', max_length=20, null=True, verbose_name='Dung lượng pin'),
        ),
    ]
